### ISSUE TITLE
Do there any blockers to bump new release?

### ISSUE THREAD

**Issue by jramnai** [django-webtest/django-webtest#118]
We are looking forward to using `django-webtest` with Django 3.2 on [edX](https://github.com/edx).

Required PR - #117  is already merged into the master branch.
Do there any chance a new version will be bumped soon?

If any blockers with the release I would be happy to help.

Thank you in advance.

**Comment by gawel** [comment]
Looks like the travis hook is "dead" because they moved to travis-ci.com. I didn't realise that before merging your PR.
The problem is that nothing tells that everything is ok (except by running tox locally and I wont install postgres).

Dont know how to fix that. I moved most of my projects to github actions.

May be this should be done for this project too.

If you want to give it a try... let me know. I'll try to dig into that myself otherwise.

Example here: https://github.com/gawel/irc3/blob/master/.github/workflows/tox.yml

**Comment by jramnai** [comment]
> If you want to give it a try... let me know. I'll try to dig into that myself otherwise.

I will give it a try.

**Comment by jramnai** [comment]
@gawel, I don't have the capacity to move tests GitHub Actions.

**Comment by gawel** [comment]
Firts step done: https://github.com/django-webtest/django-webtest/actions/runs/1308239423

Just needs to add postgres

**Comment by gawel** [comment]
Everything is now running smoothly. I've released 1.9.8
